---
detect_relations: true
options:
  collate: utf8_general_ci
  charset: utf8
  type: InnoDB

Products:
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    title:
      type: string(125)
      default: null
    title_plain:
      type: string(125)
      default: null
    price:
      type: float
      notnull: true
    brand_price:
      type: float
      notnull: true
    detail:
      type: clob(65535)
      default: null
    status:
      type: integer(1)
      default: null
    view:
      type: integer(4)
      default: null
    created_date:
      type: timestamp
      default: null
    product_brands_id:
      type: integer(4)
      notnull: true
    product_categories_id:
      type: integer(4)
      notnull: true
    product_type_id:
      type: integer(4)
      notnull: true
    gender_id:
      type: integer(4)
      notnull: true
  relations:
    ProductCategories:
      class: ProductCategories
      local: product_categories_id
      foreign: id
      foreignAlias: Products
      foreignType: many
      owningSide: true
  indexes:
    fk_products_product_brands1:
      fields: [product_brands_id]
    fk_products_product_categories1:
      fields: [product_categories_id]
    fk_products_product_type1:
      fields: [product_type_id]
    fk_products_gender1:
      fields: [gender_id]
  options:
    charset: utf8
    collate: utf8_general_ci
    type: MyISAM

ProductCategories:
  tableName: product_categories
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    title:
      type: string(125)
      default: null
    title_plain:
      type: string(125)
      default: null
    orders:
      type: integer(4)
      default: null
    status:
      type: integer(1)
      default: null
    children_id:
      type: string(125)
      notnull: true
    root_id:
      type: integer(4)
      notnull: true
    product_categories_id:
      type: integer(4)
      notnull: true
    product_type_id:
      type: integer(4)
      notnull: true
    gender_id:
      type: integer(4)
      notnull: true
  relations:
    ProductCategories:
      class: ProductCategories
      local: product_categories_id
      foreign: id
      foreignAlias: ProductCategories
      foreignType: many
      owningSide: true
  indexes:
    fk_product_categories_product_categories:
      fields: [product_categories_id]
    fk_product_categories_product_type1:
      fields: [product_type_id]
    fk_product_categories_gender1:
      fields: [gender_id]
    fk_product_categories_product_categories1:
      fields: [product_categories_id, id]
  options:
    charset: utf8
    collate: utf8_general_ci
    type: MyISAM

Members:
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    username:
      type: string(45)
      default: null
    password:
      type: string(125)
      default: null
    name:
      type: string(45)
      default: null
    email:
      type: string(125)
      default: null
    created_date:
      type: timestamp
      default: null
    last_login:
      type: timestamp
      default: null
    status:
      type: integer(1)
      default: null
    tel:
      type: string(45)
      default: null
    mobile:
      type: string(45)
      default: null
  options:
    charset: utf8
    collate: utf8_general_ci
    type: MyISAM

Contents:
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    title:
      type: string(256)
      default: null
    title_plain:
      type: string(256)
      default: null
    description:
      type: clob(65535)
      default: null
    detail:
      type: clob(65535)
      default: null
    status:
      type: integer(1)
      default: null
    created_date:
      type: timestamp
      default: null
    view:
      type: integer(4)
      default: null
    categories_id:
      type: integer(4)
      notnull: true
    members_id:
      type: integer(4)
      notnull: true
    author:
      type: string(125)
      default: null
  indexes:
    fk_contents_categories:
      fields: [categories_id]
    fk_contents_members1:
      fields: [members_id]
  options:
    charset: utf8
    collate: utf8_general_ci
    type: MyISAM

Contact:
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    name_title:
      type: string(45)
      default: null
    name:
      type: string(45)
      default: null
    email:
      type: string(45)
      default: null
    phone:
      type: string(45)
      default: null
    booking_id:
      type: string(45)
      default: null
    subject:
      type: string(125)
      default: null
    content:
      type: clob(16777215)
      default: null
    created_date:
      type: timestamp
      default: null
    viewed:
      type: integer(1)
      default: null
    ip:
      type: string(15)
      default: null
  options:
    charset: utf8
    collate: utf8_general_ci
    type: MyISAM

