<?php

/**
 * Adv
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Adv extends BaseAdv
{
	public static $Location = array('0'=>'Logo','1'=>'Banner_Middle','2'=>'Top Bander','3'=>'Bander sản phẩm','4'=>'Quảng cáo trang sản phẩm','5'=>'Quảng cáo trang chủ');
	public function getLocation() {
		return self::$Location[$this->location];
	}
	public static function getAll($Condition = array(), $currentPage = 1, $recordPerPage, $order = 'active , id DESC') {
	
		$Adv = Doctrine_Query::create ()->from ( __CLASS__ )->orderBy ( $order );
		foreach ( $Condition as $key => $item ) {
			$Adv->addWhere ( $key, $item );
		}
		$pager = new Doctrine_Pager ( $Adv, $currentPage, $recordPerPage );
		$Data = $pager->execute ();
		return array ($pager, $Data );
	}
	
	public static function getAllWithoutPager($Condition = array(),$limit = 0) {
		$Adv = Doctrine_Query::create ()->from ( __CLASS__ )->orderBy ( 'id DESC' )->limit($limit);
		foreach ( $Condition as $key => $item ) {
			$Adv->addWhere ( $key, $item );
		}
		return $Adv->execute ();
	}
	public static function getById($id = 0) {
		return Doctrine_Query::create ()->from ( __CLASS__ )->where ( 'id=?', $id )->execute ()->getFirst ();
	}
	
	public static function DeleteById($id = 0) {
		//echo Doctrine_Query::create ()->delete ( __CLASS__ )->where ( 'id=?', $id )->getSqlQuery();
		Doctrine_Query::create ()->delete ( __CLASS__ )->where ( 'id=?', $id )->execute ();
	}
	public function getThumbImage(){
		return '/uploads/'.$this->file;
	}
}