 	
    	<div class="leftcol">
        	 <?php echo $this->partial('index/boxcate.phtml')?>
           <?php echo $this->partial('index/boxhotline.phtml')?>

	         </div><!--e: div.leftcol-->
    	<div class="maincol">
        	<div class="introduction">
            	<div class="background">
                	<h1>Giới thiệu</h1>
                	<br/>
                     <p class="alink"><span><b><?php echo $this->News->title?></b> <label class="datepost">(<?php echo date('d/m/Y',strtotime($this->News->created_date))?>)</label></span></p>
                    	<div class="textnone">
                        	<p class="normal"><?php echo $this->News->detail?></p>
                        	<?php if($this->News->author):?>
                            <p align="right" class="clr999"><i style="font-size:13px">Theo nguồn: <?php echo $this->News->author?></i></p>
                            <?php endif;?>
                        </div>
                   
                 </div>
                                   	  	<h2>Tin khác</h2>
		                    <ul>
		                    <?php foreach ($this->NewsList as $News):?>
		                    	<li><span><a href="<?php echo $News->getLink('Giới thiệu')?>"><?php echo $News->title?></a> <label class="datepost">(<?php echo date('d/m/Y',strtotime($News->created_date))?>)</label></span></li>
		                   <?php endforeach;?>
	                    	</ul>
                               
                </div>
            </div><!--@introduction-->
            
        </div><!--e: div.maincol-->
   
        
        <script type="text/javascript" language="javascript">
$(function() {
	$("#gioithieu").addClass('cur');
});
</script>    